import Header from '@/components/Header/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeContextProvider } from '@/components/themeToggle/ThemeContext'
import ThemeProvider from '@/components/themeToggle/ThemeProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeContextProvider>
					<ThemeProvider>
						<Header />
						{children}
					</ThemeProvider>
				</ThemeContextProvider>
			</body>
		</html>
	)
}
